---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin4
  namespace: pgadmin4
spec:
  type: ClusterIP
  selector:
    access: external
  ports:
    - name: pgadmin4-http
      port: 80
      targetPort: 5050
