version: "3.7"

services:
  postgres:
    image: "postgres:11.2-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "./docker-compose/postgres/data/:/var/lib/postgresql/data/"
      - "./docker-compose/postgres/docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_PASSWORD: "password"
  redis:
    image: "redis:5.0.3-alpine"
    ports:
      - "6379:6379"
    volumes:
      - "./docker-compose/redis/data/:/data/"
