---
apiVersion: v1
kind: Service
metadata:
  name: sentry
  namespace: sentry
spec:
  type: ClusterIP
  selector:
    role: dashboard
    access: external
  ports:
    - name: sentry-http
      port: 80
      targetPort: 9000
