---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-config
  namespace: kube-system
  labels:
    group: metricbeat
data:
  metricbeat.yml: |-
    metricbeat:
      config:
        modules:
          # Mounted `metricbeat-daemonset-modules` configmap:
          path: ${path.config}/modules.d/*.yml
          # Reload module configs as they change:
          reload:
            enabled: true

    setup:
      kibana:
        protocol: "https"
        host: "kibana.mops.mediaartslab.com:443"
        ssl:
          enabled: true
      template:
        overwrite: true

    output:
      elasticsearch:
        hosts:
        - "10.16.241.84"
        - "10.16.241.83"
        - "10.16.241.88"

    monitoring:
      enabled: true
      cluster_uuid: MuXZaQPsQLurEQpzh2gSwQ
      elasticsearch:
        hosts:
        - "10.16.241.84"
        - "10.16.241.83"
        - "10.16.241.88"

    http:
      enabled: true
      host: 0.0.0.0
      port: 5066
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: metricbeat-daemonset-modules
  namespace: kube-system
  labels:
    group: metricbeat
data:
  system.yml: |-
    - module: system
      enabled: true
      period: 1m
      metricsets:
      - cpu
      - load
      - memory
      - network
      - process
      - process_summary
      - core
      - diskio
      - socket
      processes:
        - ".*"
      process:
        include_top_n:
          by_cpu: 5 # include top 5 processes by CPU
          by_memory: 5 # include top 5 processes by memory
    - module: system
      enabled: true
      period: 1m
      metricsets:
      - filesystem
      - fsstat
      processors:
      - drop_event:
          when:
            regexp:
              system:
                filesystem:
                  mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
  kubernetes.yml: |-
    - module: kubernetes
      enabled: true
      period: 1m
      metricsets:
      - "node"
      - "system"
      - "pod"
      - "container"
      - "volume"
      - "proxy"
      - "event"
      - "controllermanager"
      - "scheduler"
      add_metadata: true
      hosts:
        - "localhost:10250"
  docker.yml: |-
    - module: docker
      enabled: true
      period: 1m
      metricsets:
      - "container"
      - "cpu"
      - "diskio"
      - "event"
      - "healthcheck"
      - "info"
      - "image"
      - "memory"
      - "network"
      hosts:
      - "unix:///var/run/docker.sock"
