---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metricbeat
  namespace: kube-system
  labels:
    group: metricbeat
spec:
  selector:
    matchLabels:
      access: external
  template:
    metadata:
      labels:
        access: external
    spec:
      serviceAccountName: metricbeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: metricbeat
          image: "docker.elastic.co/beats/metricbeat:7.5.0"
          args:
            [
              "-c",
              "/etc/metricbeat/metricbeat.yml",
              "-e",
              "-system.hostfs=/hostfs",
            ]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: config
              mountPath: /etc/metricbeat/metricbeat.yml
              subPath: metricbeat.yml
            - name: modules
              mountPath: /usr/share/metricbeat/modules.d
            - name: dockersock
              mountPath: /var/run/docker.sock
            - name: proc
              mountPath: /hostfs/proc
              readOnly: true
            - name: cgroup
              mountPath: /hostfs/sys/fs/cgroup
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: config
          configMap:
            name: metricbeat-daemonset-config
        - name: modules
          configMap:
            name: metricbeat-daemonset-modules
