---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metabase-web
  namespace: metabase
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      access: external
  template:
    metadata:
      labels:
        access: external
    spec:
      containers:
        - name: metabase
          image: "metabase/metabase:v0.33.7.3"
          imagePullPolicy: IfNotPresent
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -Xmx3g
            - name: MB_JETTY_HOST
              value: "0.0.0.0"
            - name: MB_JETTY_PORT
              value: "3000"
            - name: MB_DB_CONNECTION_URI
              valueFrom:
                secretKeyRef:
                  name: runtime-secrets
                  key: POSTGRES_METABASE_URI
            - name: JAVA_TIMEZONE
              value: "UTC"
            - name: MB_EMOJI_IN_LOGS
              value: "true"
          ports:
            - name: http
              containerPort: 3000
          livenessProbe:
            httpGet:
              path: "/"
              port: 3000
            initialDelaySeconds: 120
            timeoutSeconds: 5
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: "/"
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 3
            periodSeconds: 5
