---
apiVersion: v1
kind: Service
metadata:
  name: metabase
  namespace: metabase
spec:
  type: ClusterIP
  selector:
    access: external
  ports:
    - name: metabase-http
      port: 80
      targetPort: 3000
