---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-web
  namespace: drone
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      access: external
  template:
    metadata:
      labels:
        role: dashboard
        access: external
    spec:
      containers:
        - name: web
          image: "drone/drone:1.6.4"
          imagePullPolicy: IfNotPresent
          env:
            - name: DRONE_LOGS_DEBUG
              value: "true"
            - name: DRONE_LOGS_TEXT
              value: "true"
            - name: DRONE_LOGS_PRETTY
              value: "true"
            - name: DRONE_LOGS_COLOR
              value: "true"
            - name: DRONE_DATABASE_DRIVER
              value: "postgres"
            - name: DRONE_DATABASE_DATASOURCE
              valueFrom:
                secretKeyRef:
                  name: runtime-secrets
                  key: DRONE_DATABASE_DATASOURCE
            - name: DRONE_SERVER_PROTO
              value: "https"
            - name: DRONE_SERVER_HOST
              value: "drone.mops.mediaartslab.com:80"
            - name: DRONE_USER_CREATE
              value: "username:kurtis-rainbolt-greene,machine:false,admin:true"
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: runtime-secrets
                  key: DRONE_RPC_SECRET
            - name: DRONE_GIT_ALWAYS_AUTH
              value: "true"
            - name: DRONE_GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: runtime-secrets
                  key: DRONE_GITHUB_CLIENT_ID
            - name: DRONE_GITHUB_SERVER
              value: https://github.mediaartslab.com
            - name: DRONE_GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: runtime-secrets
                  key: DRONE_GITHUB_CLIENT_SECRET
          ports:
            - name: http
              containerPort: 80
            - name: grpc
              containerPort: 9000
          livenessProbe:
            httpGet:
              path: "/"
              port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner
  namespace: drone
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  selector:
    matchLabels:
      access: external
  template:
    metadata:
      labels:
        role: runner
        access: external
    spec:
      containers:
        - name: runner
          image: drone/drone-runner-kube:latest
          ports:
            - containerPort: 3000
          env:
            - name: DRONE_DEBUG
              value: "true"
            - name: DRONE_TRACE
              value: "true"
            - name: DRONE_RPC_PROTO
              value: "https"
            - name: DRONE_RPC_HOST
              value: "drone.mops.mediaartslab.com:9000"
            - name: DRONE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: runtime-secrets
                  key: DRONE_RPC_SECRET
