---
apiVersion: v1
kind: Service
metadata:
  name: drone-web
  namespace: drone
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: grpc
      port: 9000
      targetPort: 9000
  selector:
    role: dashboard
    access: external
---
apiVersion: v1
kind: Service
metadata:
  name: drone-runner
  namespace: drone
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    role: runner
    access: external
