---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: apm-server
  namespace: apm-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apm-server
  maxReplicas: 4
  minReplicas: 2
  metrics:
    - resource:
        name: cpu
        targetAverageUtilization: 60
      type: Resource
    - resource:
        name: memory
        targetAverageUtilization: 60
      type: Resource
