---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kibana
spec:
  type: ClusterIP
  selector:
    access: external
  ports:
    - name: kibana-http
      port: 80
      targetPort: 5601
