---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ambassador
  labels:
    group: ambassador
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      group: ambassador
      role: service-mesh
  template:
    metadata:
      labels:
        group: ambassador
        role: service-mesh
    spec:
      restartPolicy: Always
      serviceAccountName: ambassador
      containers:
      - name: ambassador
        image: quay.io/datawire/ambassador:0.50.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        - containerPort: 8877
        env:
        - name: AMBASSADOR_ID
          value: default
        - name: AMBASSADOR_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        livenessProbe:
          httpGet:
            path: "/ambassador/v0/check_alive"
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: "/ambassador/v0/check_ready"
            port: 8877
          initialDelaySeconds: 30
          periodSeconds: 3
