---
apiVersion: v1
kind: Service
metadata:
  name: ambassador
  labels:
    group: ambassador
    role: service-mesh
  annotations:
    getambassador.io/config: |-
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  healthcheck
      prefix: /
      service: ambassador.default
      rewrite: /ambassador/v0/check_alive
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  server-backend
      prefix: /
      host: resources.difference-engineers.com
      service: server-backend.default
      rewrite: /ambassador/v0/diag/
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  browser-client
      prefix: /
      host: www.difference-engineers.com
      service: browser-client.default
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: couchdb-origin
      prefix: /
      host: couchdb-origin.difference-engineers.com
      service: couchdb-origin.default:5984
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: kubernetes-dashboard
      prefix: /
      host: kubernetes-dashboard.difference-engineers.com
      service: kubernetes-dashboard.kube-system
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: ambassador-admin
      prefix: /
      host: ambassador-admin.difference-engineers.com
      service: ambassador-admin.default:8877
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  grafana
      prefix: /
      host: grafana.difference-engineers.com
      service: grafana.default
      ---
      apiVersion: ambassador/v1
      kind:  Mapping
      name:  metabase
      prefix: /
      host: metabase.difference-engineers.com
      service: metabase.default
      ---
      apiVersion: ambassador/v1
      kind: Mapping
      name: sentry
      prefix: /
      host: sentry.difference-engineers.com
      service: sentry.default
spec:
  type: LoadBalancer
  selector:
    group: ambassador
  ports:
  - name: ambassador-http
    port: 80
    targetPort: 80
